### ISSUE TITLE
API Crashing

### ISSUE THREAD

**Issue by van-thieu** [SpaceXLand/api#209]
When attempting to retrieve data on all Launches related fields, the GraphQL API for SpaceX endpoint returns error.
It seems there is a limitation on the number of levels deep within the JSON hierarchy.

0: {message: "query exceeds complexity limit", locations: [{line: 1, column: 1}],…}
extensions: {code: "GRAPHQL_VALIDATION_FAILED"}
code: "GRAPHQL_VALIDATION_FAILED"
locations: [{line: 1, column: 1}]
0: {line: 1, column: 1}
column: 1
line: 1
message: "query exceeds complexity limit"

**Comment by swcarlosrj** [comment]
Thanks for reaching out @van-thieu, as you've said there's a complexity limit to ensure consistency across the API, you may try to remove some fields or make several queries to achieve your goal. Closing this for now 😊
