### ISSUE TITLE
API is not available, consider migration from heroku to fly.io

### ISSUE THREAD

**Issue by StarpTech** [SpaceXLand/api#236]
Hi @swcarlosrj :smile: It looks like the API is no longer available. Do you need a sponsor based on Heroku's recently published plans to cancel free plans? Otherwise, fly.io has a gorgeous free program, and the deployment is straightforward. You could deploy it to two different regions (US, EU) without paying a penny. If you need any help, ping me.

You could also try to contact Fly.io for OSS sponsorship if you need more. https://fly.io/docs/about/open-source/#recurring-donations

**Comment by swcarlosrj** [comment]
Working again @StarpTech, sorry for the downtime! I have been actually paying Heroku since I created it, I'll consider moving it as soon as I have time. Thanks for the suggestion!
